---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: src
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: LOCAL_PATH/containers/app/src
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi