apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sphela-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: sphela-nginx
        app: sphela
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: sphela-nginx
        image: gcr.io/sphela-153202/sphela-nginx:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    run: sphela-nginx
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: src
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/bjorn/projects/sphela/containers/app/src
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sphela-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: sphela-app
        app: sphela
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: sphela-nginx
        image: gcr.io/sphela-153202/sphela-app:v2
        ports:
        - containerPort: 9100
        volumeMounts:
            - name: src
              mountPath: /www/sphela/app/src/
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName: srclaim
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    run: sphela-app

